### ISSUE TITLE
Need accessible dataroot

### ISSUE THREAD

**Issue by AriettaZ** [AweSim-OSC/vftwebapp#86]
When I run vftwebapp as my sandbox app, it has dataroot pointing to `/var/www/ood/apps/dev/azhu/gateway/vftwebapp/data` instead of `/users/PZS0002/azhu/awesim/dev/vftwebapp/data`. As a result, vftwebapp can't run successfully.
```
/var/spool/batch/torque_quick/mom_priv/jobs/22724.quick-batch.ten.osc.edu.SC: line 64: /var/www/ood/apps/dev/azhu/gateway/vftwebapp/data/sessions/1/22724.quick-batch.ten.osc.edu.pass: No such file or directory
chmod: cannot access `/var/www/ood/apps/dev/azhu/gateway/vftwebapp/data/sessions/1/22724.quick-batch.ten.osc.edu.pass': No such file or directory
```

**Comment by ericfranz** [comment]
OOD_DATAROOT or RAILS_DATAROOT are options I think https://github.com/OSC/ood_appkit/blob/ea1435d4bbff47cd1786f84096f415441089a7f5/lib/ood_appkit/configuration.rb#L70

So you could do in a .env.development file:

OOD_DATAROOT=/users/PZS0002/azhu/awesim/dev/vftwebapp/data
